# Generated by Django 4.0.1 on 2022-01-18 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.IntegerField()),
                ('sneaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.sneaker')),
            ],
        ),
    ]
