# Generated by Django 4.0.1 on 2022-01-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_resale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'A Grade'), ('B', 'B Grade'), ('C', 'C Grade'), ('D', 'D Grade'), ('E', 'E Grade')], default='B Grade', max_length=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='resale',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='resale',
            name='date',
            field=models.DateField(verbose_name='resale date'),
        ),
        migrations.AddField(
            model_name='sneaker',
            name='conditions',
            field=models.ManyToManyField(to='main_app.Condition'),
        ),
    ]
