# Generated by Django 4.0.1 on 2022-01-18 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_condition_alter_resale_options_alter_resale_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
