# Generated by Django 4.0.1 on 2022-01-18 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_condition_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condition',
            old_name='name',
            new_name='title',
        ),
    ]
