# Generated by Django 4.0.1 on 2022-01-18 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_name_condition_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condition',
            old_name='title',
            new_name='quality',
        ),
    ]
